-- ============================================================================
-- ЦГБ №3 — автономная схема PostgreSQL (БЕЗ Supabase)
-- Генерируется: postgres-migration/build-schema.py
-- PostgreSQL 15+; повторный запуск безопасен.
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- Совместимость существующих RPC с auth.uid(). API выставляет cgb.user_id
-- только внутри транзакции после проверки JWT.
create schema if not exists auth;
create or replace function auth.uid()
returns uuid language sql stable as $$
  select nullif(current_setting('cgb.user_id', true), '')::uuid;
$$;

-- Собственная авторизация. Пароль хранится только как bcrypt-хеш.
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  password_hash text,
  user_metadata jsonb not null default '{}'::jsonb,
  email_confirmed_at timestamptz,
  password_reset_required boolean not null default true,
  disabled boolean not null default false,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists users_email_lower_uidx
  on public.users (lower(email));

create table if not exists public.refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  user_agent text,
  ip inet
);
create index if not exists refresh_tokens_user_idx on public.refresh_tokens(user_id);
create index if not exists refresh_tokens_expiry_idx on public.refresh_tokens(expires_at);


-- =====================================================================
-- 1. ТАБЛИЦЫ
-- =====================================================================

-- ---------- Пользователи и роли (обычно уже есть — на всякий случай) ----------
create table if not exists public.user_roles (
  user_id uuid primary key,
  role text,
  display_name text,
  custom_role_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_roles (
  id uuid primary key default gen_random_uuid(),
  key text unique,
  name text,
  description text,
  color text,
  permissions jsonb not null default '{}'::jsonb,
  default_perms jsonb not null default '{}'::jsonb,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Спасательные колонки (если таблицы уже созданы раньше с другим набором полей)
alter table public.user_roles add column if not exists display_name text;
alter table public.user_roles add column if not exists custom_role_id uuid;
alter table public.user_roles add column if not exists updated_at timestamptz not null default now();
alter table public.custom_roles add column if not exists id uuid;
alter table public.custom_roles add column if not exists key text;
alter table public.custom_roles add column if not exists base_role text;   -- admin / ss / user
alter table public.custom_roles add column if not exists name text;
alter table public.custom_roles add column if not exists description text;
alter table public.custom_roles add column if not exists color text;
alter table public.custom_roles add column if not exists permissions jsonb not null default '{}'::jsonb;
alter table public.custom_roles add column if not exists default_perms jsonb not null default '{}'::jsonb;
alter table public.custom_roles add column if not exists sort integer not null default 0;
alter table public.custom_roles add column if not exists updated_at timestamptz not null default now();
update public.custom_roles set id = gen_random_uuid() where id is null;
alter table public.custom_roles alter column id set default gen_random_uuid();
create unique index if not exists custom_roles_id_uidx on public.custom_roles(id);
create unique index if not exists custom_roles_key_uidx on public.custom_roles(key);

-- ---------- Контентные страницы ----------
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text,
  excerpt text,
  body text,
  tag text,
  dept text,
  image text,
  images jsonb default '[]'::jsonb,
  date date default current_date,
  author_name text,
  author_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faq (
  id bigint generated by default as identity primary key,
  title text,
  "desc" text,
  image text,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.info_page (
  id integer primary key default 1,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.ustavy (
  id bigint generated by default as identity primary key,
  slug text unique,
  title text,
  theme text,
  code text,
  meta text,
  emblem text,
  content jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now(),
  updated_by_name text
);

create table if not exists public.composition (
  id integer primary key default 1,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text
);

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  title text,
  tag text,
  image text,
  crew text,
  speed text,
  price text,
  rank text,
  purpose text,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by_name text
);

create table if not exists public.learn_materials (
  id uuid primary key default gen_random_uuid(),
  title text,
  url text,
  description text,
  category text,
  kind text,
  cover_url text,
  sort integer not null default 0,
  created_by uuid,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.train_categories (
  id uuid primary key default gen_random_uuid(),
  title text,
  parent uuid,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.train_lessons (
  id uuid primary key default gen_random_uuid(),
  title text,
  excerpt text,
  content text,
  category uuid,
  sort integer not null default 0,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.holiday_state (
  id integer primary key default 1,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text
);

-- ---------- Электронные заявления (Discord-бот → сайт) ----------
create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'discord',
  external_id text unique,              -- id сообщения Discord
  message_link text,
  app_type text,
  fields jsonb not null default '{}'::jsonb,
  raw_text text,
  submitter_name text,
  submitter_discord text,
  submitter_avatar text,
  status text not null default 'new',   -- new / approved / rejected / archived
  reject_reason text,
  responded_by uuid,
  responded_by_name text,
  responded_at timestamptz,
  result_message_id text,
  result_sent_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists applications_status_idx on public.applications (status);
create index if not exists applications_created_idx on public.applications (created_at desc);

create table if not exists public.apps_settings (
  id integer primary key default 1,
  guild_id text,
  incoming_channel_id text,
  results_channel_id text,
  ping_role_id text,
  reviewer_role_id text,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text,
  verdict_channel_id text,
  ping_role_id_2 text

);

create table if not exists public.bot_status (
  id integer primary key default 1,
  online boolean not null default false,
  tag text,
  guilds jsonb not null default '[]'::jsonb,
  last_seen timestamptz,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  version text,
  guild_name text,
  members_count integer,
  channels_count integer

);

create table if not exists public.bot_messages (
  id uuid primary key default gen_random_uuid(),
  channel_id text,
  content text,
  embed_title text,
  embed_description text,
  embed_color integer,
  embed_image_url text,
  embed_footer text,
  ping_type text,
  ping_value text,
  attachments jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  error_message text,
  sent_message_id text,
  sent_channel_id text,
  sent_at timestamptz,
  created_by uuid,
  created_by_name text,
  created_at timestamptz not null default now()
);


-- ---------- Жалобы ----------
create sequence if not exists public.complaints_code_seq start 1;

create table if not exists public.complaints (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  values jsonb not null default '{}'::jsonb,
  submitter_fio text,
  submitter_static text,
  submitter_discord text,
  target_fio text,
  target_static text,
  target_discord_id text,
  evidence_url text,
  status text not null default 'new',   -- new / decided / withdrawn
  verdict_kind text,
  verdict text,
  verdict_comment text,
  verdict_at timestamptz,
  verdict_by_uid uuid,
  verdict_by_name text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ds_channel_id text,
  ds_message_id text,
  verdict_ds_message_id text,
  edited_at timestamptz,
  edited_by_uid uuid,
  edited_by_name text

);
create index if not exists complaints_status_idx on public.complaints (status);
create index if not exists complaints_created_idx on public.complaints (created_at desc);

create table if not exists public.complaint_history (
  id uuid primary key default gen_random_uuid(),
  complaint_id uuid references public.complaints(id) on delete cascade,
  action text,
  changed_by_uid uuid,
  changed_by_name text,
  changes jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.complaint_form (
  id integer primary key default 1,
  title text,
  intro text,
  fields jsonb not null default '[]'::jsonb,
  channels jsonb not null default '{}'::jsonb,
  ping_role_id text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

-- ---------- Заявки (отгулы, отпуска, повышения и т.д.) ----------
create sequence if not exists public.requests_code_seq start 1;

create table if not exists public.requests (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  kind text,
  values jsonb not null default '{}'::jsonb,
  submitter_uid uuid,
  submitter_fio text,
  submitter_static text,
  submitter_discord text,
  status text not null default 'pending',  -- pending / approved / rejected
  verdict_comment text,
  verdict_at timestamptz,
  verdict_by_uid uuid,
  verdict_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ds_channel_id text,
  ds_message_id text,
  ds_message_id_2 text

);
create index if not exists requests_kind_idx on public.requests (kind);
create index if not exists requests_status_idx on public.requests (status);
create index if not exists requests_created_idx on public.requests (created_at desc);

create table if not exists public.request_forms (
  id text primary key,                   -- leave / vacation_ic / dismissal / ...
  title text,
  description text,
  fields jsonb not null default '[]'::jsonb,
  rank_matrix jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  channel_id text,
  verdict_channel_id text,
  ping_role_id text,
  ping_role_id_2 text
);

create table if not exists public.requests_settings (
  id integer primary key default 1,
  max_leave_minutes integer not null default 60,
  min_leave_rank text,
  min_vac_rank text,
  channels jsonb not null default '{}'::jsonb,
  ping_roles jsonb not null default '{}'::jsonb,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  min_rank_leave text,
  min_rank_vacation text,
  max_vacation_days integer,
  weekday_start text,
  weekday_end text,
  weekend_end text,
  holiday_end text,
  lunch_start text,
  lunch_end text,
  poverka_time text,
  poverka_window_min integer,
  block_if_violations boolean,
  notify_verdict boolean,
  supply_score jsonb
);

-- ---------- Нарушения / наказания (реестр + запросы АБ) ----------
create table if not exists public.violations_registry (
  id uuid primary key default gen_random_uuid(),
  code text unique,
  target_fio text,
  target_static text,
  target_discord_id text,
  target_position text,
  kind text,                             -- warn / reproach / talk / confinement / uval
  reason text,
  evidence_url text,
  complaint_id uuid,
  status text not null default 'active', -- active / pending / refused / removed
  notify_mode text,
  expires_at timestamptz,
  confinement_minutes integer,
  issued_by_uid uuid,
  issued_by_name text,
  issued_by_discord_id text,
  requested_by_uid uuid,
  requested_by_name text,
  requested_by_static text,
  requested_by_discord_id text,
  reviewed_by_uid uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,
  reviewer_comment text,
  removed_at timestamptz,
  removed_by_uid uuid,
  removed_by_name text,
  removed_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ds_channel_id text,
  ds_message_id text,
  verdict_ds_message_id text,
  removed_ds_message_id text,
  requested_at timestamptz,
  request_source text,
  request_extra jsonb,
  escalated_from jsonb,
  confinement_hours numeric,
  requested_by_position text

);
create index if not exists violations_status_idx on public.violations_registry (status);

create table if not exists public.violations_history (
  id uuid primary key default gen_random_uuid(),
  violation_id uuid references public.violations_registry(id) on delete cascade,
  action text,
  status text,
  before_data jsonb,
  after_data jsonb,
  comment text,
  changed_by_uid uuid,
  changed_by_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.violations_settings (
  id integer primary key default 1,
  verdict_channel_id text,
  orders_channel_id text,
  ping_role_id text,
  confinement_default_minutes integer,
  data jsonb not null default '{}'::jsonb,
  active_kinds jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  complaints_channel_id text,
  verdicts_channel_id text,
  report_channel_id text,
  confinement_channel_id text,
  removal_channel_id text,
  expire_warn_days integer,
  expire_reproach_days integer,
  expire_talk_days integer,
  expire_confinement_hours integer,
  expire_confinement_minutes integer,
  warn_to_reproach_threshold integer
);

-- ---------- Проверки АБ ----------
create table if not exists public.vp_checks (
  discord_id text primary key,
  medbook text,
  narko text,
  driver text,
  passport text,
  personal_file text,
  weapon_license text,
  attestation text,
  evidence_url text,
  notes text,
  checked_by uuid,
  checked_by_name text,
  checked_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.vp_settings (
  id integer primary key default 1,
  guild_id text,
  report_channel_id text,
  report_channel_name text,
  ping_role_id text,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create table if not exists public.vp_role_mapping (
  role_id text primary key,
  dept text,
  rank text,
  updated_at timestamptz not null default now(),
  show text,
  role_kind text,
  kind text,
  label text,
  sort integer
);

create table if not exists public.vp_reports (
  id uuid primary key default gen_random_uuid(),
  archive_id uuid,
  fio text,
  static_id text,
  discord_id text,
  dept text,
  status text,
  notes text,
  checked_at timestamptz,
  checked_by_name text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.vp_archive (
  id uuid primary key default gen_random_uuid(),
  title text,
  period_from timestamptz,
  period_to timestamptz,
  saved_by uuid,
  saved_by_name text,
  saved_at timestamptz not null default now(),
  snapshot jsonb,
  stats jsonb not null default '{}'::jsonb,
  members_total integer,
  members_checked integer,
  members_partial integer,
  report_message_id text,
  report_sent_at timestamptz,
  report_sent_by_name text,
  notes text,
  report_channel_id text,
  report_sent_by uuid,
  updated_at timestamptz not null default now()

);

create table if not exists public.vp_report_requests (
  id uuid primary key default gen_random_uuid(),
  archive_id uuid,
  channel_id text,
  requested_by uuid,
  requested_by_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  message text,
  sent_message_id text,
  sent_at timestamptz

);

create table if not exists public.vp_request_forms (
  id text primary key,
  label text,
  icon text,
  color integer,
  fields jsonb not null default '[]'::jsonb,
  channel_id text,
  ping_role_id text,
  active boolean not null default true,
  sort_order integer not null default 0,
  verdict_channel_id text,
  ping_role_id_2 text,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text
);

-- ---------- Еженедельные отчёты ----------
create table if not exists public.report_forms (
  id text primary key,
  label text,
  icon text,
  color integer,
  fields jsonb not null default '[]'::jsonb,
  channel_id text,
  ping_role_id text,
  active boolean not null default true,
  sort_order integer not null default 0,
  ping_role_id_2 text,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text
);

create table if not exists public.report_send_requests (
  id uuid primary key default gen_random_uuid(),
  form_id text,
  submitter_uid uuid,
  submitter_email text,
  submitter_fio text,
  submitter_static text,
  submitter_position text,
  values jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  message text,
  ds_message_id text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  ds_channel_id text,
  finished_at timestamptz,
  requested_at timestamptz not null default now()

);

-- ---------- Поставки ----------
create table if not exists public.supply_form (
  id integer primary key default 1,
  title text,
  intro text,
  fields jsonb not null default '[]'::jsonb,
  channel_id text,
  ping_role_id text,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  channel_name text,
  ping_role_name text,
  status_emoji jsonb
);

create table if not exists public.supply_requests (
  id uuid primary key default gen_random_uuid(),
  code text,
  fio text,
  static_id text,
  discord text,
  values jsonb not null default '{}'::jsonb,
  photo_url text,
  status text not null default 'pending',
  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,
  reject_reason text,
  merged_into uuid,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  channel_id text,
  message_id text,
  sent_at timestamptz,
  error_message text,
  emoji_status text,
  emoji_status_note text,
  dispute_resolution text,
  resolved_by uuid,
  resolved_by_name text,
  resolved_at timestamptz,
  replaced_at timestamptz,
  replaced_by uuid,
  replaced_by_name text

);
create index if not exists supply_requests_created_idx on public.supply_requests (created_at desc);

create table if not exists public.supply_entries (
  id uuid primary key default gen_random_uuid(),
  request_id uuid,
  static_id text,
  fio text,
  kind text,
  amount numeric,
  data jsonb not null default '{}'::jsonb,
  rejected_at timestamptz,
  rejected_by_name text,
  created_at timestamptz not null default now()
);
create index if not exists supply_entries_static_idx on public.supply_entries (static_id);

create table if not exists public.supply_rescan_requests (
  id uuid primary key default gen_random_uuid(),
  from_date date,
  to_date date,
  requested_by uuid,
  requested_by_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  message text,
  scanned integer,
  finished_at timestamptz

);

-- ---------- Тестирование ----------
create table if not exists public.test_categories (
  id uuid primary key default gen_random_uuid(),
  name text,
  color integer,
  title text,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tests (
  id uuid primary key default gen_random_uuid(),
  slug text unique,
  title text,
  description text,
  intro text,
  icon text,
  category_id uuid references public.test_categories(id) on delete set null,
  pass_score integer not null default 70,
  max_attempts integer not null default 0,
  time_limit_minutes integer,
  result_channel_id text,
  published boolean not null default false,
  show_answers_after boolean not null default false,
  shuffle_questions boolean not null default false,
  questions_per_run integer,
  sort integer not null default 0,
  created_by uuid,
  created_by_name text,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.test_questions (
  id uuid primary key default gen_random_uuid(),
  test_id uuid references public.tests(id) on delete cascade,
  prompt text,
  type text not null default 'single',
  options jsonb not null default '[]'::jsonb,
  correct jsonb not null default '[]'::jsonb,
  points integer not null default 1,
  image_url text,
  sort integer not null default 0,
  created_at timestamptz not null default now(),
  kind text,
  text text,
  images jsonb not null default '[]'::jsonb,
  option_images jsonb not null default '[]'::jsonb,
  prefilled_value text
);
create index if not exists test_questions_test_idx on public.test_questions (test_id);

create table if not exists public.test_attempts (
  id uuid primary key default gen_random_uuid(),
  test_id uuid references public.tests(id) on delete cascade,
  fio text,
  static_id text,
  discord text,
  answers jsonb not null default '{}'::jsonb,
  score integer,
  total integer,
  percent numeric,
  passed boolean,
  started_at timestamptz,
  finished_at timestamptz not null default now(),
  review_status text not null default 'pending',
  reviewed_by uuid,
  reviewed_by_name text,
  reviewed_at timestamptz,
  review_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  channel_sent_id text,
  channel_message_id text,
  channel_sent_at timestamptz

);
create index if not exists test_attempts_test_idx on public.test_attempts (test_id, finished_at desc);

create table if not exists public.test_blocks (
  id uuid primary key default gen_random_uuid(),
  test_id uuid references public.tests(id) on delete cascade,
  value text,                            -- статик или discord
  reason text,
  blocked_by uuid,
  blocked_by_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.test_ping_lines (
  id uuid primary key default gen_random_uuid(),
  test_id uuid references public.tests(id) on delete cascade,
  text text,
  sort integer not null default 0
);

create table if not exists public.test_result_requests (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid references public.test_attempts(id) on delete cascade,
  channel_id text,
  ping_discord text,
  is_repeat boolean not null default false,
  requested_by uuid,
  requested_by_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  message text,
  sent_message_id text,
  sent_at timestamptz

);

-- ---------- Премирование (бухгалтерия) ----------
create table if not exists public.payroll_drafts (
  id uuid primary key default gen_random_uuid(),
  title text,
  fund_amount numeric not null default 0,
  pct_manual boolean not null default true,
  data jsonb not null default '{"departments":[]}'::jsonb,
  status text not null default 'draft',  -- draft / sent
  sent_at timestamptz,
  sent_by uuid,
  sent_by_name text,
  ds_message_id text,
  ds_channel_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid,
  period_from date,
  period_to date

);

create table if not exists public.payroll_archive (
  id uuid primary key default gen_random_uuid(),
  title text,
  fund_amount numeric not null default 0,
  pct_manual boolean,
  data jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  sent_by uuid,
  sent_by_name text,
  ds_message_id text,
  ds_channel_id text,
  created_at timestamptz not null default now(),
  period_from date,
  period_to date

);

create table if not exists public.payroll_settings (
  id integer primary key default 1,
  channel_id text,
  ping_role_id text,
  header_text text default 'ПРИКАЗ О ПРЕМИРОВАНИИ',
  footer_text text,
  output_mode text not null default 'both',
  split_by_dept boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create table if not exists public.payroll_send_requests (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid,
  channel_id text,
  payload jsonb,
  status text not null default 'pending',
  requested_by uuid,
  requested_by_name text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  message text,
  output_mode text,
  split_by_dept boolean,
  image_data text,
  image_parts jsonb,
  finished_at timestamptz

);

-- ---------- Discord-синхронизация (заполняет бот) ----------
create table if not exists public.ds_channels (
  channel_id text primary key,
  name text,
  parent_id text,
  parent_name text,
  position integer,
  kind text,
  synced_at timestamptz not null default now(),
  type text,
  updated_at timestamptz not null default now()

);

create table if not exists public.ds_roles (
  role_id text primary key,
  name text,
  color integer,
  position integer,
  synced_at timestamptz not null default now()
);

create table if not exists public.ds_guild_roles (
  role_id text primary key,
  name text,
  color integer,
  position integer,
  synced_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ds_members (
  discord_id text primary key,
  display_name text,
  raw_nick text,
  parsed_fio text,
  parsed_static text,
  parsed_dept text,
  role_ids jsonb not null default '[]'::jsonb,
  role_names jsonb not null default '[]'::jsonb,
  avatar_url text,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists ds_members_fio_idx on public.ds_members (parsed_fio);

create table if not exists public.ds_sync_requests (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid,
  requested_by_name text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

-- Спасательные колонки для таблиц бота (если они созданы старым скриптом).
-- Бот (bot/vp.js) умеет пропускать отсутствующие колонки сам, но для полных
-- данных (аватарки, global_name, даты) лучше иметь весь набор.
alter table public.ds_roles add column if not exists updated_at timestamptz not null default now();
alter table public.ds_members add column if not exists username text;
alter table public.ds_members add column if not exists global_name text;
alter table public.ds_members add column if not exists is_bot boolean not null default false;
alter table public.ds_members add column if not exists joined_at timestamptz;
alter table public.ds_members add column if not exists last_seen timestamptz;
alter table public.ds_sync_requests add column if not exists message text;
alter table public.ds_sync_requests add column if not exists members_scanned integer;
alter table public.ds_sync_requests add column if not exists finished_at timestamptz;

-- ---------- Прочее ----------
create table if not exists public.raids_events (
  id uuid primary key default gen_random_uuid(),
  kind text,
  title text,
  ds_author_name text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  channel_id text,
  channel_name text,
  ds_message_id text,
  ds_author_id text,
  content_preview text
);

create table if not exists public.raids_settings (
  id integer primary key default 1,
  channel_success_id text,
  channel_fail_id text,
  success_role_id text,
  fail_role_id text,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

-- =====================================================================
-- 2. RPC-ФУНКЦИИ (вызываются сайтом)
-- =====================================================================

-- 2.1 Назначение роли пользователю (ЛК → «Создать аккаунт» / смена роли).
-- v3: p_role опционален — если пуст/null, базовая роль берётся из
-- переданной кастомной роли (p_custom_role_id → custom_roles.base_role),
-- иначе 'user'. Возвращает json с фактически записанной ролью.
drop function if exists public.staff_upsert_role(uuid, text, text, uuid);
create function public.staff_upsert_role(
  p_user_id uuid, p_role text default null, p_display_name text default null, p_custom_role_id uuid default null
) returns json
language plpgsql security definer set search_path = public as $$
declare
  v_cr public.custom_roles%rowtype;
  v_role text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if not exists (select 1 from public.user_roles ur where ur.user_id = auth.uid() and ur.role = 'admin')
     and exists (select 1 from public.user_roles where role = 'admin') then
    raise exception 'only admin can assign roles';
  end if;
  if p_custom_role_id is not null then
    select * into v_cr from public.custom_roles where id = p_custom_role_id;
  end if;
  v_role := coalesce(nullif(trim(coalesce(v_cr.base_role,'')),''), nullif(trim(coalesce(p_role,'')),''), 'user');
  insert into public.user_roles (user_id, role, display_name, custom_role_id, updated_at)
  values (p_user_id, v_role, nullif(p_display_name,''), v_cr.id, now())
  on conflict (user_id) do update
    set role = excluded.role,
        display_name = coalesce(excluded.display_name, public.user_roles.display_name),
        custom_role_id = excluded.custom_role_id,
        updated_at = now();
  return json_build_object('ok', true, 'user_id', p_user_id, 'role', v_role,
    'custom_role_id', v_cr.id, 'custom_role_key', v_cr.key, 'custom_role_name', v_cr.name);
end $$;

-- RPC пересоздаём через drop: у старых баз тип возврата мог быть иным,
-- а create or replace его не меняет (42P13). Политики на них не завязаны.
drop function if exists public.get_complaint_form();
drop function if exists public.submit_complaint(jsonb, text, text, text, text, text, text, text);
drop function if exists public.submit_request(text, jsonb, text, text, text);
drop function if exists public.get_supply_form();
drop function if exists public.submit_supply_request(text, text, text, jsonb);
drop function if exists public.count_test_attempts(uuid, text, text);
drop function if exists public.check_test_blocked(uuid, text, text);
drop function if exists public.submit_test_attempt(uuid, text, text, text, jsonb, integer, integer, numeric, boolean, timestamptz);
drop function if exists public.request_test_result(uuid, text, text);
drop function if exists public.ensure_payroll_draft();
drop function if exists public.archive_payroll_draft(uuid, text, text, text);

-- 2.2 Форма жалобы (публичное чтение одной строки)
create or replace function public.get_complaint_form()
returns setof public.complaint_form
language sql security definer set search_path = public stable as $$
  select * from public.complaint_form where id = 1 limit 1;
$$;

-- 2.3 Подача жалобы (анонимно)
create or replace function public.submit_complaint(
  p_values jsonb default '{}'::jsonb,
  p_submitter_fio text default null,
  p_submitter_static text default null,
  p_submitter_discord text default null,
  p_target_fio text default null,
  p_target_static text default null,
  p_target_discord_id text default null,
  p_evidence_url text default null
) returns setof public.complaints
language plpgsql security definer set search_path = public as $$
declare
  v_code text;
begin
  v_code := 'Ж' || lpad(nextval('public.complaints_code_seq')::text, 5, '0');
  return query
    insert into public.complaints (code, values, submitter_fio, submitter_static, submitter_discord,
                                   target_fio, target_static, target_discord_id, evidence_url, status)
    values (v_code, coalesce(p_values,'{}'::jsonb), p_submitter_fio, p_submitter_static, p_submitter_discord,
            p_target_fio, p_target_static, p_target_discord_id, p_evidence_url, 'new')
    returning *;
end $$;

-- 2.4 Подача заявки (отгул/отпуск/увольнение/повышение/восстановление)
create or replace function public.submit_request(
  p_kind text, p_values jsonb default '{}'::jsonb,
  p_fio text default null, p_static text default null, p_discord text default null
) returns setof public.requests
language plpgsql security definer set search_path = public as $$
declare
  v_code text;
begin
  v_code := 'З' || lpad(nextval('public.requests_code_seq')::text, 5, '0');
  return query
    insert into public.requests (code, kind, values, submitter_fio, submitter_static, submitter_discord,
                                 submitter_uid, status)
    values (v_code, p_kind, coalesce(p_values,'{}'::jsonb), p_fio, p_static, p_discord, auth.uid(), 'pending')
    returning *;
end $$;

-- 2.5 Форма поставки
create or replace function public.get_supply_form()
returns setof public.supply_form
language sql security definer set search_path = public stable as $$
  select * from public.supply_form where id = 1 limit 1;
$$;

-- 2.6 Подача заявки на поставку
create or replace function public.submit_supply_request(
  p_fio text, p_static text, p_discord text default null, p_values jsonb default '{}'::jsonb
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
begin
  insert into public.supply_requests (fio, static_id, discord, values, status)
  values (p_fio, p_static, p_discord, coalesce(p_values,'{}'::jsonb), 'pending')
  returning id into v_id;
  return v_id;
end $$;

-- 2.7 Количество попыток теста
create or replace function public.count_test_attempts(
  p_test_id uuid, p_static text default null, p_discord text default null
) returns integer
language sql security definer set search_path = public stable as $$
  select count(*)::integer from public.test_attempts a
  where a.test_id = p_test_id
    and ((p_static is not null and lower(a.static_id) = lower(p_static))
      or (p_discord is not null and lower(a.discord) = lower(p_discord)));
$$;

-- 2.8 Проверка блокировки
create or replace function public.check_test_blocked(
  p_test_id uuid, p_static text default null, p_discord text default null
) returns text
language sql security definer set search_path = public stable as $$
  select b.reason from public.test_blocks b
  where (b.test_id = p_test_id or b.test_id is null)
    and ((p_static is not null and lower(b.value) = lower(p_static))
      or (p_discord is not null and lower(b.value) = lower(p_discord)))
  order by b.created_at desc limit 1;
$$;

-- 2.9 Отправка результата прохождения теста
create or replace function public.submit_test_attempt(
  p_test_id uuid, p_fio text, p_static text, p_discord text default null,
  p_answers jsonb default '{}'::jsonb, p_score integer default null,
  p_max integer default null, p_percent numeric default null,
  p_passed boolean default null, p_started timestamptz default now()
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
  v_blocked text;
  v_max int;
  v_count int;
begin
  select public.check_test_blocked(p_test_id, p_static, p_discord) into v_blocked;
  if v_blocked is not null then
    raise exception 'blocked: %', v_blocked;
  end if;
  select t.max_attempts into v_max from public.tests t where t.id = p_test_id;
  if v_max is not null and v_max > 0 then
    select public.count_test_attempts(p_test_id, p_static, p_discord) into v_count;
    if v_count >= v_max then
      raise exception 'max attempts reached';
    end if;
  end if;
  insert into public.test_attempts (test_id, fio, static_id, discord, answers, score, total,
                                    percent, passed, started_at, finished_at, review_status)
  values (p_test_id, p_fio, p_static, p_discord, coalesce(p_answers,'{}'::jsonb), p_score, p_max,
          p_percent, p_passed, coalesce(p_started, now()), now(), 'pending')
  returning id into v_id;
  return v_id;
end $$;

-- 2.10 Запрос результата теста в Discord (обрабатывает бот)
create or replace function public.request_test_result(
  p_attempt_id uuid, p_channel_id text default null, p_ping_discord text default null
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
begin
  insert into public.test_result_requests (attempt_id, channel_id, ping_discord, status)
  values (p_attempt_id, p_channel_id, p_ping_discord, 'pending')
  returning id into v_id;
  return v_id;
end $$;

-- 2.11 Получить (или создать) черновик премирования
create or replace function public.ensure_payroll_draft()
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_id uuid;
begin
  select d.id into v_id from public.payroll_drafts d
  where d.status = 'draft' order by d.created_at desc limit 1;
  if v_id is null then
    insert into public.payroll_drafts (title, status, data, pct_manual, updated_at)
    values ('Реестр премирования от ' || to_char(now(), 'DD.MM.YYYY'), 'draft',
            '{"departments":[]}'::jsonb, true, now())
    returning id into v_id;
  end if;
  return v_id;
end $$;

-- 2.12 Архивировать черновик премирования после отправки
create or replace function public.archive_payroll_draft(
  p_id uuid, p_ds_msg_id text default null, p_ds_ch_id text default null, p_sent_by_name text default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  update public.payroll_drafts
     set status = 'sent', sent_at = now(),
         sent_by = auth.uid(), sent_by_name = p_sent_by_name,
         ds_message_id = p_ds_msg_id, ds_channel_id = p_ds_ch_id,
         updated_at = now()
   where id = p_id;
  insert into public.payroll_archive (title, fund_amount, pct_manual, data, sent_at,
                                      sent_by, sent_by_name, ds_message_id, ds_channel_id)
  select d.title, d.fund_amount, d.pct_manual, d.data, now(),
         auth.uid(), p_sent_by_name, p_ds_msg_id, p_ds_ch_id
    from public.payroll_drafts d where d.id = p_id;
end $$;

-- Контент страниц сайта (Услуги, Медикаменты и др.): читают все,
-- запись — админ или делегированное право (site:edit / services:edit / meds:edit).
-- Строки НЕ сидим: страницы берут встроенный дефолт, если записи нет.
create table if not exists public.site_data (
  key text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

-- 2.0 Проверка «вызывающий — админ» (security definer — не рекурсирует в RLS)
create or replace function public.is_admin()
returns boolean
language sql security definer stable set search_path = public as $$
  select exists(select 1 from public.user_roles where user_id = auth.uid() and role = 'admin');
$$;

-- Права на выполнение RPC

alter table public.payroll_drafts  add column if not exists period_from date;
alter table public.payroll_drafts  add column if not exists period_to date;
alter table public.payroll_archive add column if not exists period_from date;
alter table public.payroll_archive add column if not exists period_to date;
-- Премирование: поля отправки (картинка/текст, части, финиш)
alter table public.payroll_send_requests add column if not exists message text;
alter table public.payroll_send_requests add column if not exists output_mode text;
alter table public.payroll_send_requests add column if not exists split_by_dept boolean;
alter table public.payroll_send_requests add column if not exists image_data text;
alter table public.payroll_send_requests add column if not exists image_parts jsonb;
alter table public.payroll_send_requests add column if not exists finished_at timestamptz;

-- Архив проверок АБ: канал/автор отправки отчёта
alter table public.vp_archive add column if not exists report_channel_id text;
alter table public.vp_archive add column if not exists report_sent_by uuid;
-- Запросы «отправить отчёт проверки» в Discord
alter table public.vp_report_requests add column if not exists message text;
alter table public.vp_report_requests add column if not exists sent_message_id text;
alter table public.vp_report_requests add column if not exists sent_at timestamptz;

-- Еженедельные отчёты: отправка в Discord
alter table public.report_send_requests add column if not exists ds_channel_id text;
alter table public.report_send_requests add column if not exists finished_at timestamptz;
alter table public.report_send_requests add column if not exists requested_at timestamptz not null default now();

-- Результаты тестов: отправка в Discord
alter table public.test_result_requests add column if not exists message text;
alter table public.test_result_requests add column if not exists sent_message_id text;
alter table public.test_result_requests add column if not exists sent_at timestamptz;
alter table public.test_attempts add column if not exists channel_sent_id text;
alter table public.test_attempts add column if not exists channel_message_id text;
alter table public.test_attempts add column if not exists channel_sent_at timestamptz;

-- Поставки: статусы по реакциям и привязка сообщения
alter table public.supply_requests add column if not exists channel_id text;
alter table public.supply_requests add column if not exists message_id text;
alter table public.supply_requests add column if not exists sent_at timestamptz;
alter table public.supply_requests add column if not exists error_message text;
alter table public.supply_requests add column if not exists emoji_status text;
alter table public.supply_requests add column if not exists emoji_status_note text;
alter table public.supply_rescan_requests add column if not exists message text;
alter table public.supply_rescan_requests add column if not exists scanned integer;
alter table public.supply_rescan_requests add column if not exists finished_at timestamptz;

-- Заявления с форм сайта: привязка сообщений в Discord (заявка + вердикт)
alter table public.requests add column if not exists ds_channel_id text;
alter table public.requests add column if not exists ds_message_id text;
alter table public.requests add column if not exists ds_message_id_2 text;

-- Жалобы: привязка сообщений + вердикт
alter table public.complaints add column if not exists ds_channel_id text;
alter table public.complaints add column if not exists ds_message_id text;
alter table public.complaints add column if not exists verdict_ds_message_id text;

-- Реестр нарушений: сообщения в Discord + поля запросов наказаний
alter table public.violations_registry add column if not exists ds_channel_id text;
alter table public.violations_registry add column if not exists ds_message_id text;
alter table public.violations_registry add column if not exists verdict_ds_message_id text;
alter table public.violations_registry add column if not exists removed_ds_message_id text;
alter table public.violations_registry add column if not exists requested_at timestamptz;
alter table public.violations_registry add column if not exists request_source text;
alter table public.violations_registry add column if not exists request_extra jsonb;
alter table public.violations_registry add column if not exists escalated_from jsonb;

-- Настройки приёма заявлений: сайт использует verdict_channel_id и ping_role_id_2
alter table public.apps_settings add column if not exists verdict_channel_id text;
alter table public.apps_settings add column if not exists ping_role_id_2 text;

-- Каналы Discord (селекторы каналов в настройках сайта)
alter table public.ds_channels add column if not exists type text;
alter table public.ds_channels add column if not exists updated_at timestamptz not null default now();

-- Статус бота (heartbeat для значка «бот онлайн» на сайте)
alter table public.bot_status add column if not exists version text;
alter table public.bot_status add column if not exists guild_name text;
alter table public.bot_status add column if not exists members_count integer;
alter table public.bot_status add column if not exists channels_count integer;
alter table public.bot_status add column if not exists updated_at timestamptz not null default now();

-- Очередь исходящих сообщений бота (сайт → Discord)

alter table public.request_forms add column if not exists channel_id text;
alter table public.request_forms add column if not exists verdict_channel_id text;
alter table public.request_forms add column if not exists ping_role_id text;
alter table public.request_forms add column if not exists ping_role_id_2 text;
alter table public.request_forms add column if not exists rank_matrix jsonb;

-- Общие настройки заявок (время, лимиты, уведомления)
alter table public.requests_settings add column if not exists min_rank_leave text;
alter table public.requests_settings add column if not exists min_rank_vacation text;
alter table public.requests_settings add column if not exists max_vacation_days integer;
alter table public.requests_settings add column if not exists weekday_start text;
alter table public.requests_settings add column if not exists weekday_end text;
alter table public.requests_settings add column if not exists weekend_end text;
alter table public.requests_settings add column if not exists holiday_end text;
alter table public.requests_settings add column if not exists lunch_start text;
alter table public.requests_settings add column if not exists lunch_end text;
alter table public.requests_settings add column if not exists poverka_time text;
alter table public.requests_settings add column if not exists poverka_window_min integer;
alter table public.requests_settings add column if not exists block_if_violations boolean;
alter table public.requests_settings add column if not exists notify_verdict boolean;
alter table public.requests_settings add column if not exists supply_score jsonb;

-- Формы запросов наказаний АБ
alter table public.vp_request_forms add column if not exists verdict_channel_id text;
alter table public.vp_request_forms add column if not exists ping_role_id_2 text;
alter table public.vp_request_forms add column if not exists updated_at timestamptz not null default now();
alter table public.vp_request_forms add column if not exists updated_by uuid;
alter table public.vp_request_forms add column if not exists updated_by_name text;

-- Реестр нарушений: срок ДЗ в часах (совместимость), позиция запросившего
alter table public.violations_registry add column if not exists confinement_hours numeric;
alter table public.violations_registry add column if not exists requested_by_position text;

-- Настройки нарушений: каналы публикации/вердиктов/снятий и пороги эскалации
alter table public.violations_settings add column if not exists complaints_channel_id text;
alter table public.violations_settings add column if not exists verdicts_channel_id text;
alter table public.violations_settings add column if not exists report_channel_id text;
alter table public.violations_settings add column if not exists confinement_channel_id text;

-- История изменений нарушений (если база собрана старыми скриптами,
-- таблицы/колонок могло не быть — правки запросов «не сохранялись» молча)
alter table public.violations_history add column if not exists violation_id uuid;
alter table public.violations_history add column if not exists action text;
alter table public.violations_history add column if not exists status text;
alter table public.violations_history add column if not exists before_data jsonb;
alter table public.violations_history add column if not exists after_data jsonb;
alter table public.violations_history add column if not exists comment text;
alter table public.violations_history add column if not exists changed_by_uid uuid;
alter table public.violations_history add column if not exists changed_by_name text;
alter table public.violations_history add column if not exists created_at timestamptz not null default now();
do $$ begin
  if not exists (select 1 from pg_indexes where schemaname='public' and indexname='violations_history_viol_idx') then
    create index violations_history_viol_idx on public.violations_history (violation_id);
  end if;
end $$;
alter table public.violations_settings add column if not exists removal_channel_id text;
alter table public.violations_settings add column if not exists expire_warn_days integer;
alter table public.violations_settings add column if not exists expire_reproach_days integer;
alter table public.violations_settings add column if not exists expire_talk_days integer;
alter table public.violations_settings add column if not exists expire_confinement_hours integer;
alter table public.violations_settings add column if not exists warn_to_reproach_threshold integer;

-- Жалобы: вердикт (сайт пишет verdict; ранее была только verdict_kind)
alter table public.complaints add column if not exists verdict text;

-- Формы еженедельных отчётов
alter table public.report_forms add column if not exists ping_role_id_2 text;
alter table public.report_forms add column if not exists updated_at timestamptz not null default now();
alter table public.report_forms add column if not exists updated_by uuid;
alter table public.report_forms add column if not exists updated_by_name text;

-- Поставки: имена канала/роли, эмодзи статусов; решение по спорным
alter table public.supply_form add column if not exists channel_name text;
alter table public.supply_form add column if not exists ping_role_name text;
alter table public.supply_form add column if not exists status_emoji jsonb;
alter table public.supply_requests add column if not exists dispute_resolution text;
alter table public.supply_requests add column if not exists resolved_by uuid;
alter table public.supply_requests add column if not exists resolved_by_name text;
alter table public.supply_requests add column if not exists resolved_at timestamptz;

-- Вопросы тестов: сайт хранит kind/text/images/prefilled_value
alter table public.test_questions add column if not exists kind text;
alter table public.test_questions add column if not exists text text;
alter table public.test_questions add column if not exists images jsonb not null default '[]'::jsonb;
alter table public.test_questions add column if not exists option_images jsonb not null default '[]'::jsonb;
alter table public.test_questions add column if not exists prefilled_value text;

-- Привязка ролей Discord к отделам/должностям (страница проверок АБ)
alter table public.vp_role_mapping add column if not exists show text;
alter table public.vp_role_mapping add column if not exists role_kind text;
alter table public.vp_role_mapping add column if not exists kind text;
alter table public.vp_role_mapping add column if not exists label text;
alter table public.vp_role_mapping add column if not exists sort integer;

-- Роли сервера (читают премия и автоподстановка): метка обновления
alter table public.ds_guild_roles add column if not exists updated_at timestamptz not null default now();

-- Рейды: события от бота + настройки детектора
alter table public.raids_events add column if not exists channel_id text;
alter table public.raids_events add column if not exists channel_name text;
alter table public.raids_events add column if not exists ds_message_id text;
alter table public.raids_events add column if not exists ds_author_id text;
alter table public.raids_events add column if not exists content_preview text;

create table if not exists public.raids_settings (
  id integer primary key default 1,
  channel_success_id text,
  channel_fail_id text,
  success_role_id text,
  fail_role_id text,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

alter table public.violations_settings add column if not exists expire_confinement_minutes integer;

-- проверки АБ: название канала отчётов (для подписи на сайте)
alter table public.vp_settings add column if not exists report_channel_name text;

-- настройки заявлений: кто последний менял
alter table public.apps_settings add column if not exists updated_by_name text;

-- поставки: «замена поставки»
alter table public.supply_requests add column if not exists replaced_at timestamptz;
alter table public.supply_requests add column if not exists replaced_by uuid;
alter table public.supply_requests add column if not exists replaced_by_name text;

-- жалобы: кто и когда правил карточку после создания
alter table public.complaints add column if not exists edited_at timestamptz;
alter table public.complaints add column if not exists edited_by_uid uuid;
alter table public.complaints add column if not exists edited_by_name text;

-- архив проверок АБ: правка записи
alter table public.vp_archive add column if not exists updated_at timestamptz;

-- категории тестов: сайт работает с name/color (title оставлен для совместимости)
alter table public.test_categories add column if not exists name text;
alter table public.test_categories add column if not exists color integer;
-- старые базы держали название в title — переносим (только если колонка title есть)
do $$
begin
  if exists(select 1 from information_schema.columns
            where table_schema='public' and table_name='test_categories' and column_name='title') then
    update public.test_categories set name = title where name is null and title is not null;
  end if;
end $$;

-- уставы: обложка документа (тема, подпись meta, эмблема)
alter table public.ustavy add column if not exists theme text;
alter table public.ustavy add column if not exists meta text;
alter table public.ustavy add column if not exists emblem text;


-- Предусловия RPC: колонки, к которым обращаются функции.
-- На базах, где таблица создана стабом блока 0 — достраиваем;
-- где уже есть — add column if not exists ничего не меняет.
-- жалобы
alter table public.complaints add column if not exists code text;
alter table public.complaints add column if not exists values jsonb;
alter table public.complaints add column if not exists submitter_fio text;
alter table public.complaints add column if not exists submitter_static text;
alter table public.complaints add column if not exists submitter_discord text;
alter table public.complaints add column if not exists target_fio text;
alter table public.complaints add column if not exists target_static text;
alter table public.complaints add column if not exists target_discord_id text;
alter table public.complaints add column if not exists evidence_url text;
alter table public.complaints add column if not exists status text;
-- заявки персонала
alter table public.requests add column if not exists code text;
alter table public.requests add column if not exists kind text;
alter table public.requests add column if not exists values jsonb;
alter table public.requests add column if not exists submitter_fio text;
alter table public.requests add column if not exists submitter_static text;
alter table public.requests add column if not exists submitter_discord text;
alter table public.requests add column if not exists submitter_uid uuid;
alter table public.requests add column if not exists status text;
-- поставки
alter table public.supply_requests add column if not exists fio text;
alter table public.supply_requests add column if not exists static_id text;
alter table public.supply_requests add column if not exists discord text;
alter table public.supply_requests add column if not exists values jsonb;
alter table public.supply_requests add column if not exists status text;
-- тесты
alter table public.tests add column if not exists max_attempts integer;
alter table public.test_attempts add column if not exists test_id uuid;
alter table public.test_attempts add column if not exists fio text;
alter table public.test_attempts add column if not exists static_id text;
alter table public.test_attempts add column if not exists discord text;
alter table public.test_attempts add column if not exists answers jsonb;
alter table public.test_attempts add column if not exists score integer;
alter table public.test_attempts add column if not exists total integer;
alter table public.test_attempts add column if not exists percent numeric;
alter table public.test_attempts add column if not exists passed boolean;
alter table public.test_attempts add column if not exists started_at timestamptz;
alter table public.test_attempts add column if not exists finished_at timestamptz;
alter table public.test_attempts add column if not exists review_status text;
alter table public.test_blocks add column if not exists test_id uuid;
alter table public.test_blocks add column if not exists kind text;
alter table public.test_blocks add column if not exists value text;
alter table public.test_blocks add column if not exists reason text;
alter table public.test_blocks add column if not exists created_at timestamptz;
alter table public.test_result_requests add column if not exists attempt_id uuid;
alter table public.test_result_requests add column if not exists channel_id text;
alter table public.test_result_requests add column if not exists ping_discord text;
alter table public.test_result_requests add column if not exists status text;

-- ---------- ПОЛНЫЙ АУДИТ КОЛОНОК ТЕСТОВ ----------
-- Сайт пишет эти поля через upsert/rpc; если таблица пришла из старой
-- версии скриптов (или создана заглушкой), колонки может не хватать —
-- сайт ловит «Could not find the ... column ... schema cache».
create table if not exists public.test_ping_lines (id uuid primary key default gen_random_uuid());

alter table public.tests add column if not exists slug text;
alter table public.tests add column if not exists title text;
alter table public.tests add column if not exists description text;
alter table public.tests add column if not exists intro text;
alter table public.tests add column if not exists icon text;
alter table public.tests add column if not exists category_id uuid;
alter table public.tests add column if not exists pass_score integer not null default 70;
alter table public.tests add column if not exists time_limit_minutes integer;
alter table public.tests add column if not exists result_channel_id text;
alter table public.tests add column if not exists published boolean not null default false;
alter table public.tests add column if not exists show_answers_after boolean not null default false;
alter table public.tests add column if not exists shuffle_questions boolean not null default false;
alter table public.tests add column if not exists questions_per_run integer;
alter table public.tests add column if not exists sort integer not null default 0;
alter table public.tests add column if not exists created_by uuid;
alter table public.tests add column if not exists created_by_name text;
alter table public.tests add column if not exists author_name text;
alter table public.tests add column if not exists created_at timestamptz not null default now();
alter table public.tests add column if not exists updated_at timestamptz not null default now();

alter table public.test_categories add column if not exists sort integer not null default 0;
alter table public.test_categories add column if not exists created_at timestamptz not null default now();

alter table public.test_questions add column if not exists test_id uuid;
alter table public.test_questions add column if not exists prompt text;
alter table public.test_questions add column if not exists type text not null default 'single';
alter table public.test_questions add column if not exists options jsonb not null default '[]'::jsonb;
alter table public.test_questions add column if not exists correct jsonb not null default '[]'::jsonb;
alter table public.test_questions add column if not exists points integer not null default 1;
alter table public.test_questions add column if not exists image_url text;
alter table public.test_questions add column if not exists sort integer not null default 0;
alter table public.test_questions add column if not exists created_at timestamptz not null default now();

alter table public.test_attempts add column if not exists reviewed_by uuid;
alter table public.test_attempts add column if not exists reviewed_by_name text;
alter table public.test_attempts add column if not exists reviewed_at timestamptz;
alter table public.test_attempts add column if not exists review_history jsonb not null default '[]'::jsonb;
alter table public.test_attempts add column if not exists created_at timestamptz not null default now();

alter table public.test_blocks add column if not exists blocked_by uuid;
alter table public.test_blocks add column if not exists blocked_by_name text;

alter table public.test_ping_lines add column if not exists test_id uuid;
alter table public.test_ping_lines add column if not exists text text;
alter table public.test_ping_lines add column if not exists sort integer not null default 0;

alter table public.test_result_requests add column if not exists is_repeat boolean not null default false;
alter table public.test_result_requests add column if not exists requested_by uuid;
alter table public.test_result_requests add column if not exists requested_by_name text;
alter table public.test_result_requests add column if not exists processed_at timestamptz;
alter table public.test_result_requests add column if not exists created_at timestamptz not null default now();
-- премирование (ensure/archive RPC)
alter table public.payroll_drafts add column if not exists title text;
alter table public.payroll_drafts add column if not exists status text;
alter table public.payroll_drafts add column if not exists data jsonb;
alter table public.payroll_drafts add column if not exists pct_manual boolean;
alter table public.payroll_drafts add column if not exists fund_amount numeric;
alter table public.payroll_drafts add column if not exists created_at timestamptz;
alter table public.payroll_drafts add column if not exists sent_at timestamptz;
alter table public.payroll_drafts add column if not exists sent_by uuid;
alter table public.payroll_drafts add column if not exists sent_by_name text;
alter table public.payroll_drafts add column if not exists ds_message_id text;
alter table public.payroll_drafts add column if not exists ds_channel_id text;
alter table public.payroll_archive add column if not exists title text;
alter table public.payroll_archive add column if not exists fund_amount numeric;
alter table public.payroll_archive add column if not exists pct_manual boolean;
alter table public.payroll_archive add column if not exists data jsonb;
alter table public.payroll_archive add column if not exists sent_at timestamptz;
alter table public.payroll_archive add column if not exists sent_by uuid;
alter table public.payroll_archive add column if not exists sent_by_name text;
alter table public.payroll_archive add column if not exists ds_message_id text;
alter table public.payroll_archive add column if not exists ds_channel_id text;


-- FAQ использует структурированные поля редактора сайта.
alter table public.faq add column if not exists cat text;
alter table public.faq add column if not exists q text;
alter table public.faq add column if not exists a text;
alter table public.faq alter column sort type bigint using sort::bigint;

-- Используется upsert блокировки по тройке полей.
create unique index if not exists test_blocks_test_kind_value_uidx
  on public.test_blocks(test_id, kind, value);

-- =====================================================================
-- ЦГБ №3 · Telegram-уведомления
-- Входит в общую автономную схему PostgreSQL.
-- Скрипт идемпотентный: его можно безопасно запускать повторно.
-- =====================================================================

create table if not exists public.telegram_settings (
  id smallint primary key default 1 check (id = 1),
  enabled boolean not null default false,
  routes jsonb not null default '{}'::jsonb,
  activated_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid,
  updated_by_name text
);

create table if not exists public.telegram_topics (
  chat_id bigint not null,
  thread_id bigint not null default 0,
  chat_title text,
  topic_title text,
  chat_type text,
  is_forum boolean not null default false,
  registered_by_name text,
  last_seen_at timestamptz not null default now(),
  primary key (chat_id, thread_id)
);

create table if not exists public.telegram_notifications (
  id uuid primary key default gen_random_uuid(),
  event_key text not null unique,
  route_key text not null,
  event_kind text not null,
  source_table text,
  source_id text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamptz,
  telegram_message_id bigint,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists telegram_notifications_queue_idx
  on public.telegram_notifications (status, created_at);
create index if not exists telegram_notifications_route_idx
  on public.telegram_notifications (route_key, created_at desc);

create table if not exists public.telegram_bot_status (
  id smallint primary key default 1 check (id = 1),
  online boolean not null default false,
  bot_id bigint,
  bot_username text,
  bot_name text,
  version text,
  last_seen_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now()
);

insert into public.telegram_settings (id, enabled, routes)
values (1, false, '{}'::jsonb)
on conflict (id) do nothing;

insert into public.telegram_bot_status (id, online)
values (1, false)
on conflict (id) do nothing;

-- Сайт видит настройки только для администратора. Секретный токен здесь
-- никогда не хранится: он остаётся только в EnvironmentFile на VPS.

create or replace function public.tg_queue_application()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kind text;
  v_key text;
begin
  if tg_op = 'INSERT' then
    v_kind := 'created';
    v_key := 'applications:' || new.id::text || ':created';
  elsif new.status is distinct from old.status then
    v_kind := 'status_' || coalesce(new.status, 'unknown');
    v_key := 'applications:' || new.id::text || ':' || v_kind || ':' || txid_current()::text;
  else
    return new;
  end if;

  insert into public.telegram_notifications
    (event_key, route_key, event_kind, source_table, source_id, payload)
  values (
    v_key, 'applications', v_kind, 'applications', new.id::text,
    jsonb_build_object(
      'id', new.id, 'app_type', new.app_type,
      'submitter_name', new.submitter_name,
      'submitter_discord', new.submitter_discord,
      'status', new.status, 'reject_reason', new.reject_reason,
      'responded_by_name', new.responded_by_name,
      'created_at', new.created_at, 'responded_at', new.responded_at
    )
  ) on conflict (event_key) do nothing;
  return new;
end;
$$;

drop trigger if exists tg_applications_notify on public.applications;
create trigger tg_applications_notify
after insert or update of status on public.applications
for each row execute function public.tg_queue_application();

-- Заявки персонала. Маршруты соответствуют темам, указанным заказчиком.
create or replace function public.tg_queue_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_route text;
  v_kind text;
  v_key text;
begin
  v_route := case new.kind
    when 'promotion' then 'promotion'
    when 'restoration' then 'applications'
    when 'dismissal' then 'dismissal'
    when 'vacation_ic' then 'vacations'
    when 'vacation_ooc' then 'vacations'
    when 'leave' then 'leave'
    else null
  end;
  if v_route is null then return new; end if;

  if tg_op = 'INSERT' then
    v_kind := 'created';
    v_key := 'requests:' || new.id::text || ':created';
  elsif new.status is distinct from old.status then
    v_kind := 'status_' || coalesce(new.status, 'unknown');
    v_key := 'requests:' || new.id::text || ':' || v_kind || ':' || txid_current()::text;
  else
    return new;
  end if;

  insert into public.telegram_notifications
    (event_key, route_key, event_kind, source_table, source_id, payload)
  values (
    v_key, v_route, v_kind, 'requests', new.id::text,
    jsonb_build_object(
      'id', new.id, 'code', new.code, 'kind', new.kind,
      'values', coalesce(new.values, '{}'::jsonb),
      'submitter_fio', new.submitter_fio,
      'submitter_static', new.submitter_static,
      'submitter_discord', new.submitter_discord,
      'status', new.status, 'verdict_comment', new.verdict_comment,
      'verdict_by_name', new.verdict_by_name,
      'created_at', new.created_at, 'verdict_at', new.verdict_at
    )
  ) on conflict (event_key) do nothing;
  return new;
end;
$$;

drop trigger if exists tg_requests_notify on public.requests;
create trigger tg_requests_notify
after insert or update of status on public.requests
for each row execute function public.tg_queue_request();

-- Завершённые экзамены / тесты.
create or replace function public.tg_queue_test_attempt()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
begin
  if new.finished_at is null then return new; end if;
  if tg_op = 'UPDATE' and old.finished_at is not null then return new; end if;

  select t.title into v_title from public.tests t where t.id = new.test_id;
  insert into public.telegram_notifications
    (event_key, route_key, event_kind, source_table, source_id, payload)
  values (
    'test_attempts:' || new.id::text || ':finished',
    'exams', 'finished', 'test_attempts', new.id::text,
    jsonb_build_object(
      'id', new.id, 'test_id', new.test_id, 'test_title', v_title,
      'fio', new.fio, 'static_id', new.static_id, 'discord', new.discord,
      'score', new.score, 'total', new.total, 'percent', new.percent,
      'passed', new.passed, 'finished_at', new.finished_at
    )
  ) on conflict (event_key) do nothing;
  return new;
end;
$$;

drop trigger if exists tg_test_attempts_notify on public.test_attempts;
create trigger tg_test_attempts_notify
after insert or update of finished_at on public.test_attempts
for each row execute function public.tg_queue_test_attempt();


alter table public.telegram_notifications
  add column if not exists net_request_id bigint,
  add column if not exists dispatched_at timestamptz;

alter table public.telegram_bot_status
  add column if not exists update_request_id bigint,
  add column if not exists update_offset bigint not null default 0;

-- 4.1 СИСТЕМНЫЕ РОЛИ (пресеты прав). key = системный идентификатор.
--     Старший состав (ключ ss) применяется автоматически всем, у кого
--     базовая роль в user_roles = 'ss'. Операторы назначаются админом
--     через ЛК → панель ролей.
-- =====================================================================

insert into public.custom_roles (key, base_role, name, description, color, permissions, default_perms, sort)
values
('admin','admin','Администратор',
 'Полный доступ ко всем разделам и настройкам',
 '#dc2626',
 '{
   "apps":{"view":true,"edit":true,"delete":true},
   "complaints":{"view":true,"review":true,"form_edit":true,"settings":true},
   "registry":{"view":true,"add":true,"edit":true,"remove":true},
   "requests":{"view":true,"review":true,"settings":true},
   "vp_request":{"submit":true,"review":true,"settings":true},
   "vp":{"view":true,"edit":true,"delete":true,"settings":true},
   "vp_archive":{"view":true,"edit":true,"delete":true,"send":true,"settings":true},
   "report":{"view":true,"submit":true,"settings":true},
   "payroll":{"view":true,"edit":true,"settings":true},
   "tests":{"view":true,"edit":true,"delete":true,"create":true,"stats":true,"reset_attempts":true},
   "supply":{"view":true,"stats":true,"admin":true,"replace":true},
   "messages":{"send":true},
   "docs":{"view":true},
   "lk":{"users":true,"roles":true,"settings":true},
   "info":{"edit":true},"ustav":{"edit":true},"services":{"edit":true},"meds":{"edit":true},
   "site":{"edit":true},
   "composition":{"view":true,"edit":true},
   "autopark":{"edit":true},"faq":{"edit":true},"training":{"edit":true},
   "learn":{"view":true,"edit":true},
   "news":{"view":true,"create":true,"edit":true,"delete":true}
 }'::jsonb,'{}'::jsonb,0),
('ss','ss','Старший состав',
 'Доступ ко всем служебным разделам без настроек',
 '#0891b2',
 '{
   "apps":{"view":true,"edit":true,"delete":true},
   "complaints":{"view":true,"review":true,"form_edit":true},
   "registry":{"view":true,"add":true,"edit":true},
   "requests":{"view":true,"review":true},
   "vp_request":{"submit":true,"review":true},
   "vp":{"view":true,"edit":true,"delete":true},
   "vp_archive":{"view":true,"edit":true,"delete":true,"send":true},
   "report":{"view":true,"submit":true},
   "payroll":{"view":true,"edit":true},
   "tests":{"view":true,"edit":true,"delete":true,"create":true,"stats":true,"reset_attempts":true},
   "supply":{"view":true,"stats":true,"admin":true,"replace":true},
   "messages":{"send":true},
   "docs":{"view":true},
   "lk":{"users":true},
   "info":{"edit":true},"ustav":{"edit":true},"services":{"edit":true},"meds":{"edit":true},
   "composition":{"view":true,"edit":true},
   "autopark":{"edit":true},"faq":{"edit":true},"training":{"edit":true},
   "learn":{"view":true,"edit":true},
   "news":{"view":true,"create":true,"edit":true,"delete":true}
 }'::jsonb,'{}'::jsonb,10),
('ab_operator','ss','Оператор АБ',
 'Оператор Администрации Больницы. Проверки АБ и архив проверок',
 '#7c3aed',
 '{
   "registry":{"view":true},
   "vp_request":{"submit":true},
   "vp":{"view":true,"edit":true},
   "vp_archive":{"view":true,"edit":true,"send":true},
   "docs":{"view":true},
   "learn":{"view":true},
   "news":{"view":true}
 }'::jsonb,'{}'::jsonb,20),
('orp_operator','ss','Оператор ОРП',
 'Оператор Отдела по Работе с Персоналом. Заявления, тесты, FAQ и обучение',
 '#2563eb',
 '{
   "apps":{"view":true,"edit":true},
   "tests":{"view":true,"edit":true,"create":true,"stats":true,"reset_attempts":true},
   "docs":{"view":true},
   "faq":{"edit":true},
   "training":{"edit":true},
   "learn":{"view":true},
   "news":{"view":true}
 }'::jsonb,'{}'::jsonb,30)
on conflict (key) do update set
  name=excluded.name, description=excluded.description, color=excluded.color,
  base_role=excluded.base_role, permissions=excluded.permissions,
  sort=excluded.sort, updated_at=now();



-- Уведомления для процессов, подключённых напрямую к PostgreSQL.
create or replace function public.cgb_notify_change()
returns trigger language plpgsql as $$
declare
  payload jsonb;
  old_data jsonb := '{}'::jsonb;
  new_data jsonb := '{}'::jsonb;
begin
  -- NOTIFY ограничен 8000 байт. Передаём только ключ и прежний/новый статус;
  -- серверный клиент бота после сигнала дочитывает полную строку.
  if TG_OP in ('UPDATE','DELETE') then
    old_data := jsonb_build_object(
      'id', to_jsonb(OLD)->'id',
      'status', to_jsonb(OLD)->'status'
    );
  end if;
  if TG_OP in ('INSERT','UPDATE') then
    new_data := jsonb_build_object(
      'id', to_jsonb(NEW)->'id',
      'status', to_jsonb(NEW)->'status'
    );
  end if;
  payload := json_build_object(
    'schema', TG_TABLE_SCHEMA,
    'table', TG_TABLE_NAME,
    'event', TG_OP,
    'old', old_data,
    'new', new_data
  );
  perform pg_notify('cgb_changes', payload::text);
  return coalesce(NEW, OLD);
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'applications','bot_messages','complaints','requests','violations_registry',
    'vp_report_requests','test_result_requests','supply_requests',
    'supply_rescan_requests','ds_sync_requests','telegram_notifications'
  ] loop
    execute format('drop trigger if exists cgb_notify_change on public.%I', t);
    execute format(
      'create trigger cgb_notify_change after insert or update or delete on public.%I for each row execute function public.cgb_notify_change()',
      t
    );
  end loop;
end $$;

-- Автоматическое updated_at для собственных пользователей.
create or replace function public.cgb_touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at before update on public.users
for each row execute function public.cgb_touch_updated_at();

-- Удаление собственной учётной записи сразу отзывает роль и сессии.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='user_roles_user_id_fkey' and conrelid='public.user_roles'::regclass
  ) then
    alter table public.user_roles
      add constraint user_roles_user_id_fkey foreign key(user_id)
      references public.users(id) on delete cascade;
  end if;
end $$;

commit;
