#!/usr/bin/env python3
"""Build the standalone PostgreSQL schema from the maintained project SQL.

The generated schema deliberately excludes Supabase-only RLS roles, Storage,
Realtime publications, pg_cron and pg_net.  Authentication is provided by the
local API and auth.uid() is emulated through a transaction-local setting so the
existing application RPC functions keep their semantics.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).with_name("01-schema.sql")


def lines(name: str, start: int, end: int) -> str:
    source = (ROOT / name).read_text(encoding="utf-8").splitlines()
    return "\n".join(source[start - 1 : end])


def strip_supabase_grants(sql: str) -> str:
    kept: list[str] = []
    for line in sql.splitlines():
        if re.match(r"^\s*(grant|revoke)\b", line, re.I):
            continue
        if re.match(r"^\s*notify\s+pgrst\b", line, re.I):
            continue
        kept.append(line)
    return "\n".join(kept)


header = r"""-- ============================================================================
-- ЦГБ №3 — автономная схема PostgreSQL (БЕЗ Supabase)
-- Генерируется: postgres-migration/build-schema.py
-- PostgreSQL 15+; повторный запуск безопасен.
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- Совместимость существующих RPC с auth.uid(). API выставляет cgb.user_id
-- только внутри транзакции после проверки JWT.
create schema if not exists auth;
create or replace function auth.uid()
returns uuid language sql stable as $$
  select nullif(current_setting('cgb.user_id', true), '')::uuid;
$$;

-- Собственная авторизация. Пароль хранится только как bcrypt-хеш.
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  password_hash text,
  user_metadata jsonb not null default '{}'::jsonb,
  email_confirmed_at timestamptz,
  password_reset_required boolean not null default true,
  disabled boolean not null default false,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists users_email_lower_uidx
  on public.users (lower(email));

create table if not exists public.refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  user_agent text,
  ip inet
);
create index if not exists refresh_tokens_user_idx on public.refresh_tokens(user_id);
create index if not exists refresh_tokens_expiry_idx on public.refresh_tokens(expires_at);
"""

# Canonical tables + RPCs + site_data/is_admin.  The next section in the old
# file is Supabase RLS, so it is intentionally not copied.
base = lines("SUPABASE-SETUP.sql", 16, 1227)
base = base.replace("create extension if not exists pgcrypto;", "-- pgcrypto enabled above", 1)
base = base.replace("generated always as identity", "generated by default as identity")

# Additions discovered during production operation.  These ranges contain
# only schema completion and no Supabase publications/policies.
fix_columns = "\n\n".join(
    [
        lines("SUPABASE-FIX.sql", 395, 474),
        lines("SUPABASE-FIX.sql", 513, 625),
        lines("SUPABASE-FIX.sql", 672, 709),
        lines("SUPABASE-FIX.sql", 719, 850),
    ]
)
fix_columns += r"""

-- FAQ использует структурированные поля редактора сайта.
alter table public.faq add column if not exists cat text;
alter table public.faq add column if not exists q text;
alter table public.faq add column if not exists a text;
alter table public.faq alter column sort type bigint using sort::bigint;

-- Используется upsert блокировки по тройке полей.
create unique index if not exists test_blocks_test_kind_value_uidx
  on public.test_blocks(test_id, kind, value);
"""

# Telegram tables and queue-producing triggers are ordinary PostgreSQL and
# remain useful; delivery itself is handled by telegram_worker.py.
telegram = "\n\n".join(
    [
        lines("SUPABASE-UPDATE-telegram.sql", 1, 74),
        lines("SUPABASE-UPDATE-telegram.sql", 114, 249),
        lines("SUPABASE-UPDATE-telegram-relay.sql", 14, 20),
    ]
)
telegram = re.sub(r"^\s*(begin|commit)\s*;\s*$", "", telegram, flags=re.I | re.M)
telegram = telegram.replace(
    "-- Выполнить целиком в Supabase → SQL Editor один раз.",
    "-- Входит в общую автономную схему PostgreSQL.",
)

role_seed = lines("SUPABASE-SETUP.sql", 1400, 1485)

footer = r"""

-- Уведомления для процессов, подключённых напрямую к PostgreSQL.
create or replace function public.cgb_notify_change()
returns trigger language plpgsql as $$
declare
  payload jsonb;
  old_data jsonb := '{}'::jsonb;
  new_data jsonb := '{}'::jsonb;
begin
  -- NOTIFY ограничен 8000 байт. Передаём только ключ и прежний/новый статус;
  -- серверный клиент бота после сигнала дочитывает полную строку.
  if TG_OP in ('UPDATE','DELETE') then
    old_data := jsonb_build_object(
      'id', to_jsonb(OLD)->'id',
      'status', to_jsonb(OLD)->'status'
    );
  end if;
  if TG_OP in ('INSERT','UPDATE') then
    new_data := jsonb_build_object(
      'id', to_jsonb(NEW)->'id',
      'status', to_jsonb(NEW)->'status'
    );
  end if;
  payload := json_build_object(
    'schema', TG_TABLE_SCHEMA,
    'table', TG_TABLE_NAME,
    'event', TG_OP,
    'old', old_data,
    'new', new_data
  );
  perform pg_notify('cgb_changes', payload::text);
  return coalesce(NEW, OLD);
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'applications','bot_messages','complaints','requests','violations_registry',
    'vp_report_requests','test_result_requests','supply_requests',
    'supply_rescan_requests','ds_sync_requests','telegram_notifications'
  ] loop
    execute format('drop trigger if exists cgb_notify_change on public.%I', t);
    execute format(
      'create trigger cgb_notify_change after insert or update or delete on public.%I for each row execute function public.cgb_notify_change()',
      t
    );
  end loop;
end $$;

-- Автоматическое updated_at для собственных пользователей.
create or replace function public.cgb_touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at before update on public.users
for each row execute function public.cgb_touch_updated_at();

-- Удаление собственной учётной записи сразу отзывает роль и сессии.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='user_roles_user_id_fkey' and conrelid='public.user_roles'::regclass
  ) then
    alter table public.user_roles
      add constraint user_roles_user_id_fkey foreign key(user_id)
      references public.users(id) on delete cascade;
  end if;
end $$;

commit;
"""

schema = "\n\n".join(
    [
        header,
        strip_supabase_grants(base),
        strip_supabase_grants(fix_columns),
        strip_supabase_grants(telegram),
        strip_supabase_grants(role_seed),
        footer,
    ]
)
OUT.write_text(schema.strip() + "\n", encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
